### PR TITLE
Add Oracle regexp_like(), regexp_count(), regexp_instr() and regexp_substr() functions. 

### PR DESCRIPTION
**Pull request by darold**
They correspond to the Oracle behavior and consist in plpgsql
functions based on PG regexp_matches(). All details of the implementation
is explained in the documentation. This patch also include a regression
test regexp_func.sql including the Oracle queries and results in comment.

### CODE REVIEW

**Comment by okbob** [comment]
This patch looks great. Unfortunately, there are some issues. 

1.  regress tests fails on PostgreSQL 9.5, 9.6
2. SELECT INTO is used, although it is not necessary. It can be useless overhead. Please, see
<pre>
postgres=# do $$
declare x int;
begin
  for i in 1..100000
  loop
    x := 10;
  end loop;
end;
$$;
DO
Time: 7,160 ms
postgres=# do $$
declare x int;
begin
  for i in 1..100000
  loop
    select 10 into x;
  end loop;
end;
$$;
DO
Time: 238,031 ms
</pre>

Regress tests I can fix easily after merging, but can you clean code from not necessary SELECT INTO? 

Big thanks for regress tests and documentation.

**Comment by darold** [comment]
Ok, I was not aware of such overhead, I will fix it tomorrow. Also I must admit that I have not run test on 9.x versions.

**Comment by okbob** [comment]
pá 5. 3. 2021 v 21:15 odesílatel Gilles Darold <notifications@github.com>
napsal:

> Ok, I was not aware of such overhead, I will fix it tomorrow. Also I must
> admit that I have not run test on 9.x versions.
>
I am on Pg 14 - and Tom did a lot of significant improvements in simple
expressions evaluation in pg 13 and pg 14.But anyway, SELECT should be used
for queries.

**Comment by darold** [comment]
Hi Pavel, I have fixed the SELECT INTO and also the port to PG 9.5 in this new commit.

**Comment by okbob** [comment]
so 6. 3. 2021 v 11:00 odesílatel Gilles Darold <notifications@github.com>
napsal:

> Hi Pavel, I have fixed the SELECT INTO and also the port to PG 9.5 in this
> new commit.
>

I see and I wrote comment

Pavel

**Comment by darold** [comment]
In this commit I have not change the assignment with position() and length(), let me know if they have to be rewritten for the style.

**Comment by okbob** [comment]
so 6. 3. 2021 v 11:20 odesílatel Gilles Darold <notifications@github.com>
napsal:

> In this commit I have not change the assignment with position() and
> length(), let me know if they have to be rewritten for the style.
>

This is not a too technical issue - originally there was no technical
difference between expression and query in PLpgSQL. Later there were a lot
of optimizations, and expressions are evaluated differently than queries.
My rule is - so everything that is not an expression is a query, and then
it should look like a query. But functions that have subquery arguments are
exactly on the border (if I understand well to your question) - the
subquery there is explicitly written, and probably it is ok.

so

a) a := fx ((SELECT ... LIMIT))

looks correct for me (minimally for readability) , but from a technical
perspective, it is not 100% correct, because expression is evaluated like a
query if any part is a query (in PLpGSQL).

b) a := (SELECT fx ((x) ..) is more exact

But I have not too strong an opinion about it. The code should be readable,
and show to highlight all important things - probably @b is a little bit
better.

What do you think about it?

**Comment by okbob** [comment]
so 6. 3. 2021 v 11:38 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
napsal:

>
>
> so 6. 3. 2021 v 11:20 odesílatel Gilles Darold <notifications@github.com>
> napsal:
>
>> In this commit I have not change the assignment with position() and
>> length(), let me know if they have to be rewritten for the style.
>>
>
> This is not a too technical issue - originally there was no technical
> difference between expression and query in PLpgSQL. Later there were a lot
> of optimizations, and expressions are evaluated differently than queries.
> My rule is - so everything that is not an expression is a query, and then
> it should look like a query. But functions that have subquery arguments are
> exactly on the border (if I understand well to your question) - the
> subquery there is explicitly written, and probably it is ok.
>
> so
>
> a) a := fx ((SELECT ... LIMIT))
>
> looks correct for me (minimally for readability) , but from a technical
> perspective, it is not 100% correct, because expression is evaluated like a
> query if any part is a query (in PLpGSQL).
>
> b) a := (SELECT fx ((x) ..) is more exact
>
> But I have not too strong an opinion about it. The code should be
> readable, and show to highlight all important things - probably @b is a
> little bit better.
>

but in this case the readability is more important - code should be
readable is major dogma.

**Comment by darold** [comment]
Thanks Pavel for your explanations, this is the orafce rules so I must conform to it :-) new commit bedeb3f fix the assignments with position() and length(). Seriously these rules looks good for me. I had not this kind of exigences with assignment as I have always used SELECT INTO with queries but I have noticed that this is not good for performances. I will try to take them as mine in further plpgsql development.

**Comment by okbob** [comment]
Thank yo very much

**Comment by okbob** [comment]
I merged the code, but I found a one significant issue

in oracle.translate_oracle_modifiers(text, bool)

you do

  IF multiline = NULL THEN
    modifiers := modifiers || 'p';
  END IF;

This is surely wrong, but when I try to fix it to

IF multiline IS NULL THEN

then regress tests are broken. Please, can you check it?

I will fix it, and I will fix the test too. But I don't know what should be
correct. I am not expert on regexps

Probably

  multiline := (SELECT regexp_matches(modifiers, 's') LIMIT 1);

  -- Oracle default behavior is newline-sensitive,
  -- PostgreSQL not, so force 'p' modifier to affect
  -- newline-sensitivity but not ^ and $ search.
  IF multiline IS NULL THEN
    modifiers := modifiers || 'p';
  END IF;

This code can be rewritten to

IF strpos(modifiers, 's') = 0 THEN
   modifiers := modifiers || 'p';
END IF.

it is much faster. Regexp functions in pg are fast, but more expensive than
others, and it is multiplied when this is set as a returning function. If
it is possible, then use functions, that returns an arrays than functions
returns table.

Pavel

**Comment by darold** [comment]
haha :-) , I've warned you that the functions have the similar behavior as Oracle. This function adds the 'p' modifier because with Oracle the default is:
- A period (.) does not match the newline character.
- The source string is treated as a single line.
which is different of the default behavior of PostgreSQL.

Flag 'p' allows these functions to respect these behaviors, when multi-line is requested the 'p' flag must not be forced. If you don't set it you will not have the same result and then the regression test fail.

If you don't trust this code, check the statement in an Oracle terminal to verify the result. This is why I have added the original Oracle queries in comment and the expected result at end of the statement after `->`. The only behavior that I've not respected is the return of REGEXP_LIKE which returns NULL or 1 in Oracle and false or true in this implementation. The function is only used in a WHERE clause as true or false expression but Oracle do not have boolean so so they use NULL or 1. If you think we should have the exact values returned bu Oracle we can change this but I think that boolean are more adapted to this kind of condition in PostgreSQL WHERE clause.

Note that in the patch sent to pgsql-hackers to include these functions in PG core they use the PostgreSQL default behavior so the same result is not expected.

**Comment by okbob** [comment]
I trust to you, but the line

" IF multiline = NULL THEN*" *

is surely a bug, and when I rewrote it to "IF multiline IS NULL THEN", then
regress tests were broken. So maybe there should be "IF multiline IS NOT
NULL THEN ...

Please, check it.







so 6. 3. 2021 v 19:05 odesílatel Gilles Darold <notifications@github.com>
napsal:

**Comment by darold** [comment]
ouch, right I've not take attention to the condition. I will check that, thanks.

**Pull request merged**
