### PR TITLE
Add the REMAINDER function that is Oracle compatible

### PR DESCRIPTION
**Pull request by pborne**
This is an Oracle compatible implementation of the REMAINDER function.

### CODE REVIEW

**Comment by okbob** [comment]
Thank you for PR 

I have two objection:

1. minimally bigint version can be easily rewritten in C - it will be significantly faster
2. missing regress tests

**Comment by okbob** [comment]
looks so this implementation is not correct - for arguments (-44, -10) it returns 6, but oracle returns -4 (tested on http://sqlfiddle.com)

**Comment by okbob** [comment]
https://github.com/orafce/orafce/commit/24bc119e84cfa0237faf9d496bce57b4fc205e8d

**Comment by pborne** [comment]
> Thank you for PR
> 
> I have two objection:
> 
> 1. minimally bigint version can be easily rewritten in C - it will be significantly faster
> 2. missing regress tests

So, how do you decide whether to implement in C or as a SQL / plPgSQL function? For instance, the MOD function is already implemented in plPgSQL. It could be implemented in C as well.

**Comment by pborne** [comment]
> 

I see now that the MOD function is just doing a simple test and calls the original MOD function in pg_catalog.

**Comment by okbob** [comment]
ne 2. 10. 2022 v 21:33 odesílatel Patrice Borne ***@***.***>
napsal:

> Thank you for PR
>
> I have two objection:
>
>    1. minimally bigint version can be easily rewritten in C - it will be
>    significantly faster
>    2. missing regress tests
>
> So, how do you decide whether to implement in C or as a SQL / plPgSQL
> function? For instance, the MOD function is already implemented in plPgSQL.
> It could be implemented in C as well.
>
I did this work already. You can see it in the last PR.

The simple function in SQL language is inlined. Then the runtime overhead
is very low. So typically, there is no problem with performance. PL/pgSQL
functions are not inlined ever. I did some tests, and the C implementation
of the "remainder" function against PLpgSQL is about 6x faster. In the end,
the SQL language can be used too, but I wrote it already.

CREATE OR REPLACE FUNCTION oracle.remainder(anyelement, anyelement)
RETURNS anyelement AS $$
SELECT $1 - round($1/($2::double precision)) * $2;
$$ LANGUAGE sql

It dependency, how you want to fix some corner cases, then C implementation
can make more sense. But for basic purposes this can be ok. These simple
routines are not good to implement in PL/pgSQL. It will be significantly
slower. The important keyword in this context is "inlining".

**Pull request closed without merging**
