### PR TITLE
Add Oracle Database compatible mod funtion.

### PR DESCRIPTION
**Pull request by nori-shinoda**
This Pull Request adds a MOD function that is compatible with Oracle Database. Oracle Database's MOD function returns the first parameter if the second parameter is zero, but PostgreSQL raises a Div/0 error.
Regards,
Noriyoshi Shinoda

### CODE REVIEW

**Comment by okbob** [comment]
There are some garbage in the patch. There is not necessity to update parser.

**Comment by nori-shinoda** [comment]
Thank you for your comment. I restored the note.

**Comment by okbob** [comment]
The files sqlparse.c
<https://github.com/orafce/orafce/pull/179/files#diff-68ffb4ba529139dbaefba57eea579e4f4f9f4e3f0df2ff1f11f54172d3c6eeee>
and sqlparse.h are useless in this context



ne 1. 5. 2022 v 15:55 odesílatel Noriyoshi Shinoda ***@***.***>
napsal:

**Comment by nori-shinoda** [comment]
Oh, thank you for pointing out.
I'm not sure why sqlparse.c and sqlparse.h have changed, but I've reverted them.

**Comment by okbob** [comment]
Looks well now, merged

Thank you for PR

**Pull request merged**
