### PR TITLE
mark  some func parallel safe

### PR DESCRIPTION
**Pull request by hslightdb**
mark round, instr, substr, length, lengthb, subtract, trunc parallel safe

### CODE REVIEW

**Comment by okbob** [comment]
you forgot to do same changes (and rename) in orafce--4.7.sql

**Comment by hslightdb** [comment]
> you forgot to do same changes (and rename) in orafce--4.7.sql

you mean add a newfile named orafce--4.8.sql?

**Comment by okbob** [comment]
When you do these changes, you should to do complete preparing for orafce--4.8. Nobody want to run update everytime

**Comment by hslightdb** [comment]
> When you do these changes, you should to do complete preparing for orafce--4.8. Nobody want to run update everytime

ok, add orafce--4.8 in  #237

**Comment by okbob** [comment]
please, update control file and increment version to 4.8 (without git tag this change is only in devel lifecycle). Drop orafce--4.7.

**Comment by okbob** [comment]
Here is conflict now, please, do new PR

**Pull request closed without merging**
